excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://adelrblog.github.io
title: lingu
tagline: log
description: adel's personal blog on science, technology, arts, and linguistics
paginate: 5
google_analytics:
    tracking_id: UA-68526002-2
github:
	Home: http://adelr.ir
