excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://adelrblog.github.io
title: through the eyes of a linguist
tagline: This is my daily blog
description: adel rahimi's personal blog
paginate: 5
