excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://adelrblog.github.io
title: lingu
tagline: log
description: əˈdelz ˈpɝrːsənl̩ ˈblɑːɡ ɑːn ˈsaɪəns tekˈnɑːlɪdʒi ˈɑːrts ənd lɪŋˈɡwɪstɪks
paginate: 5
google_analytics:
    tracking_id: UA-68526002-2
github:
    home: http://adelr.ir
