excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://adelrblog.github.io
title: Lingu
tagline: log
description: adel's personal blog on science, technology, arts, and linguistics
paginate: 5
